controller:
  installPlugins:
    - kubernetes
    - workflow-aggregator
    - git
    - configuration-as-code
    - job-dsl
  JCasC:
    defaultConfig: true
    configScripts:
      welcome-message: |
       jenkins:
         systemMessage: Welcome to Jenkins, you are. Managed as code, this instance is.
      example-job: |
        jobs:
          - script: >
              multibranchPipelineJob('jenkins-ci-job') {
                branchSources {
                  git {
                    id('jenkins-ci-job')  
                    remote('https://github.com/thangap-cloud/k8s-local-jenkins-springboot-ci.git')
                  }
                }
              }            
    securityRealm: |-
      local:
        allowsSignup: false
        enableCaptcha: false
        users:
        - id: "admin"
          name: "Jenkins Admin"
          password: "password"
    authorizationStrategy: |-
      loggedInUsersCanDoAnything:
        allowAnonymousRead: false